[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "target-feature=+avx2",
    "-C", "target-feature=+fma",
    "-C", "target-cpu=native",
    "-C", "opt-level=3",
    "-C", "codegen-units=1",
]

[target.x86_64-pc-windows-msvc]
rustflags = [
    "-C", "target-feature=+avx2",
    "-C", "target-feature=+fma",
    "-C", "target-cpu=native",
    "-C", "opt-level=3",
    "-C", "codegen-units=1",
    "-L", "C:\\Program Files (x86)\\Common Files\\Intel\\Shared Libraries\\lib",
    "-l", "OpenCL",
]

[target.x86_64-pc-windows-gnu]
rustflags = [
    "-C", "target-feature=+avx2",
    "-C", "target-feature=+fma",
    "-C", "target-cpu=native",
    "-C", "opt-level=3",
    "-C", "codegen-units=1",
]

[target.aarch64-apple-darwin]
rustflags = [
    "-C", "target-cpu=apple-m1",
    "-C", "opt-level=3",
    "-C", "codegen-units=1",
]

[target.aarch64-unknown-linux-gnu]
rustflags = [
    "-C", "target-cpu=native",
    "-C", "opt-level=3",
    "-C", "codegen-units=1",
]

[build]
jobs = 8

[net]
git-fetch-with-cli = true