[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-Z", "dylib-lto",
    "-C", "target-cpu=native",
    "-C", "opt-level=3",
    "-C", "lto=fat",
    "-C", "codegen-units=1",
    "-C", "panic=abort",
    "-C", "embed-bitcode=yes"
]

[target.x86_64-pc-windows-msvc]
rustflags = [
    "-Z", "dylib-lto",
    "-C", "target-cpu=native",
    "-C", "opt-level=3",
    "-C", "lto=fat",
    "-C", "codegen-units=1",
    "-C", "panic=abort",
]

# === Apple Silicon ===
[target.aarch64-apple-darwin]
rustflags = [
    "-Z", "dylib-lto",
    "-C", "target-cpu=apple-m1",
    "-C", "opt-level=3",
    "-C", "lto=fat",
    "-C", "codegen-units=1",
    "-C", "panic=abort",
    "-C", "embed-bitcode=yes"
]

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
overflow-checks = false
